extension_dir = "D:\master\php85\ext"
extension=openssl
extension=curl
extension=mbstring
extension=fileinfo
extension=pdo_mysql
extension=mysqli
extension=zip
extension=intl
extension=ldap
extension=gd
extension=exif
extension=php_sqlsrv_85_ts_x64.dll
extension=php_pdo_sqlsrv_85_ts_x64.dll

date.timezone = Asia/Singapore
